# This is a basic workflow to help you get started with Actions

name: Dry-Release

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 17.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 
      # Setup NodeJS
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      # Install Dependencies
      - name: Install dependencies
        run: npm install

      - name: Get Commit Message
        env:
            message: ${{ github.event.head_commit.message }}
        run: echo The commit message is ${{env.message}}
        shell: bash
      - name: Dry Release
        run: npm run dry-release
        
     
